[project]
name = 'Authoria'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Authoria]
path = 'contracts/Authoria.clar'
clarity_version = 3
epoch = 3.1

[contracts.CollaborativeCreation]
path = 'contracts/CollaborativeCreation.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
